
package ws.partner;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "GuestNotFoundException", targetNamespace = "http://ws.session.ejb/")
public class GuestNotFoundException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private GuestNotFoundException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public GuestNotFoundException_Exception(String message, GuestNotFoundException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public GuestNotFoundException_Exception(String message, GuestNotFoundException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ws.partner.GuestNotFoundException
     */
    public GuestNotFoundException getFaultInfo() {
        return faultInfo;
    }

}
