
package ws.partner;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "RoomTypeUnavailableException", targetNamespace = "http://ws.session.ejb/")
public class RoomTypeUnavailableException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private RoomTypeUnavailableException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public RoomTypeUnavailableException_Exception(String message, RoomTypeUnavailableException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public RoomTypeUnavailableException_Exception(String message, RoomTypeUnavailableException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ws.partner.RoomTypeUnavailableException
     */
    public RoomTypeUnavailableException getFaultInfo() {
        return faultInfo;
    }

}
